### ISSUE TITLE
make_thumbnail wrong answer

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#78] opened 2016-11-08 16:19 UTC
# description

a post request to `http://localhost:1024/make_thumbnail` gives the result:
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
access-control-allow-origin: http://localhost:3335
Connection: keep-alive
Keep-Alive: timeout=5, max=100
Content-Length: 0
```

The server marks the result as successful (code 200).
But the headers and body are empty, where it should (and used to) be populated with (`scripts/make_thumbnail.lua`):
```
    result = {
        nx_thumb = dims.nx,
        ny_thumb = dims.ny,
        mimetype_thumb = 'image/jpeg',
        preview_path = "http://localhost:1024/thumbs/" .. tmpname .. "_THUMB.jpg" .. "/full/full/0/default.jpg",
        filename = tmpname, -- make this a IIIF URL
        original_mimetype = mimetype,
        original_filename = filename,
        file_type = 'IMAGE'
    }
```

# context

context: run as `sudo ./build/sipi -config config/sipi.knora-config.lua`
version: 
```
$ git branch ; git log -1
  bugfixes
* develop
  master
  openssl
  wip/fix_Mac_compilation_error
commit dccdde8fa48bc2866218bb5711f8de05df95f1fa
Author: Benjamin Geer <benjaminlewis.geer@unibas.ch>
Date:   Tue Nov 8 14:46:47 2016 +0100

    Add /extsrcs/ and sipi.log*.txt to .gitignore.
```

**Comment by tobiasschweizer** [comment] 2016-11-08 17:21
Does the thumbnail get created on the disk?

**Comment by tobiasschweizer** [comment] 2016-11-08 17:45
Sipi creates the copies the file to the tmp directory, but does not create the thumbnail.

Something is wrong. I think the error happens when he thumbnail is supposed to be written:

```
print(thumbname)

myimg:write(thumbname)

print("written thumb")
```
I get the print out for the thumbname. Then the Lua script crashes.

**Comment by tobiasschweizer** [comment] 2016-11-08 17:47
This error could have been detected by running this test: `./test_server/knora_make_thumb.sh`

**Comment by lrosenth** [comment] 2016-11-15 11:07
I'm working on this – can reproduce it but the cause is still mysterious...

**Comment by tobiasschweizer** [comment] 2016-11-15 15:23
on jpegdebug branch I get the following error:

```
terminate called after throwing an instance of 'Sipi::SipiImageError'
  what():  SipiImageError in "/home/tobi/gitreps/Sipi_github/src/formats/SipiIOJpeg.cpp" #834 Message: Cannot open file "./images/thumbs/Jqh2m6anTuo-DVLhVwzXg4M_THUMB.jpg"!
Aborted (core dumped)

```

**Comment by lrosenth** [comment] 2016-11-15 21:26
Ben and I are trying to find th cause…

Lukas
--  

Prof. Dr. Lukas Rosenthaler
Head of "Digital Humanities Lab",
University of Basel
Bernoullistrasse 32
CH-4056 Basel, Switzerland

Tel: + 41 61 267 0490
Fax: +41 61 267 3855
http://www.dhlab.unibas.ch

**Comment by tobiasschweizer** [comment] 2016-12-05 07:01
that should be fixed now in `develop` (see https://github.com/dhlab-basel/Sipi/commit/66a18cc089c3cb7bfaadada6e1967d945d31ded6)

**Closed** 2017-06-30 12:28 UTC
Labels: bug
