### ISSUE TITLE
warning message: "Couldnt switch tu user !"

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#75] opened 2016-11-03 13:17 UTC
# description

When starting `Sipi`, I get the warning message:

```
[2016-11-03 14:00:17.440] [shttps-logger] [warning] Couldnt switch tu user ! You must start SIPI as root!
```

I can't read anything related on the project's page.

I tried to run it as root, but still had the same error.

# context

```
$ git branch ; git log -1
  bugfixes
* develop
  master
  openssl
  wip/fix_Mac_compilation_error
commit 839b8f3e36187d6168906c3ea774d6248ac9a72b
Merge: eb84449 dfe9935
Author: Tobias Schweizer <tobiasschweizer@users.noreply.github.com>
Date:   Wed Oct 26 14:48:25 2016 +0200

    Merge pull request #73 from dhlab-basel/wip/knora-init
```

**Comment by benjamingeer** [comment] 2016-11-03 13:30
Duplicate of #72.

**Closed by benjamingeer** 2016-11-03 13:30 UTC
Labels: duplicate
